RpaUi/Areas/Client/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RpaData.DataContext;
using RpaData.Models;

namespace RpaUi.Areas.Client.Controllers
{
    [Authorize]
    [Area("Client")]
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;
        //var clientId = User.FindFirst("ClientId").Value;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Client/Events
        public async Task<IActionResult> Index()
        {
            
            ViewBag.Greeting = "Hello";
            var clientId = Convert.ToInt32(User.FindFirst("ClientId").Value);
            return View(await _context.tblEventsHistory.Include(t=>t.Event).Where(c=>c.tblPharmacistsId == clientId).ToListAsync());
        }

        // GET: Client/Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var clientId = Convert.ToInt32(User.FindFirst("ClientId").Value);
            if (id == null)
            {
                return NotFound();
            }

            var tblEvents = await _context.tblEventsHistory.Include(t=>t.Event)
                .FirstOrDefaultAsync(m => m.Id == id);
            var eventAttendance = await _context.tblEventsHistory.AnyAsync(c => c.tblPharmacistsId == clientId && c.EventId == id);
            if (tblEvents == null)
            {
                return NotFound();
            }

            return View(tblEvents);
        }

        // GET: Client/Events/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Client/Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventName,EventStartDate,EventEndDate,EventVenue,EventPoints,EventDescription,Id,Created")] tblEvents tblEvents)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblEvents);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblEvents);
        }

        // GET: Client/Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblEvents = await _context.tblEvents.FindAsync(id);
            if (tblEvents == null)
            {
                return NotFound();
            }
            return View(tblEvents);
        }

        // POST: Client/Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventName,EventStartDate,EventEndDate,EventVenue,EventPoints,EventDescription,Id,Created")] tblEvents tblEvents)
        {
            if (id != tblEvents.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblEvents);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tblEventsExists(tblEvents.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblEvents);
        }

        // GET: Client/Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblEvents = await _context.tblEvents
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblEvents == null)
            {
                return NotFound();
            }

            return View(tblEvents);
        }

        // POST: Client/Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblEvents = await _context.tblEvents.FindAsync(id);
            _context.tblEvents.Remove(tblEvents);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Confirm(int id, bool attend)
        {
            var tblEvents = await _context.tblEvents.FindAsync(id);
            var clientId = Convert.ToInt32(User.FindFirst("ClientId").Value);

            if (tblEventsHistoryExists(id, clientId))
            {
                tblEventsHistory tblEventsHistory = await _context.tblEventsHistory.FirstOrDefaultAsync(c => c.tblPharmacistsId == clientId && c.EventId == id);
                tblEventsHistory.Attending = attend;
                _context.Update(tblEventsHistory);
                await _context.SaveChangesAsync();
            }
            else
            {
                tblEventsHistory tblEventsHistory = new tblEventsHistory();
                tblEventsHistory.tblPharmacistsId = clientId;
                tblEventsHistory.EventId = id;
                tblEventsHistory.Attending = attend;
                tblEventsHistory.Created = DateTime.Now;

                _context.Add(tblEventsHistory);
                await _context.SaveChangesAsync();
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool tblEventsExists(int id)
        {
            return _context.tblEvents.Any(e => e.Id == id);
        }

        private bool tblEventsHistoryExists(int meetingId, int clientId)
        {
            return _context.tblEventsHistory.Any(e => e.tblPharmacistsId == clientId && e.EventId == meetingId);
        }
    }
}

RpaUi/Areas/Client/Views/Events/Create.cshtml
@model RpaData.Models.tblEvents

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}

<h1>Create</h1>

<h4>tblEvents</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventStartDate" class="control-label"></label>
                <input asp-for="EventStartDate" class="form-control" />
                <span asp-validation-for="EventStartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventEndDate" class="control-label"></label>
                <input asp-for="EventEndDate" class="form-control" />
                <span asp-validation-for="EventEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventVenue" class="control-label"></label>
                <input asp-for="EventVenue" class="form-control" />
                <span asp-validation-for="EventVenue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventPoints" class="control-label"></label>
                <input asp-for="EventPoints" class="form-control" />
                <span asp-validation-for="EventPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDescription" class="control-label"></label>
                <input asp-for="EventDescription" class="form-control" />
                <span asp-validation-for="EventDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

RpaUi/Areas/Client/Views/Events/Delete.cshtml
@model RpaData.Models.tblEvents

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblEvents</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventStartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventStartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventEndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventEndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventVenue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventVenue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RpaUi/Areas/Client/Views/Events/Details.cshtml
@model RpaData.Models.tblEventsHistory

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}



<div class="content-header">
    <div class="container">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h3> @Html.DisplayFor(model => model.Event.EventName) - Details</h3>
            </div><!-- /.col -->
            <div class="col-sm-6">
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<div class="card">
    <div class="card-body">
        <div>
            <a asp-action="Index" class="btn btn-sm btn-outline-success">  <i class="fas fa-long-arrow-alt-left"></i> Back to List</a>
            @{
                if (!Model.Event.EventComplete)
                {
                    if (Model.Attending)
                    {
                        <a href="@Url.Action("Confirm", "Events", new {id = Model.Id, attend = false})" class="btn btn-sm btn-outline-danger"> <i class="far fa-thumbs-down"></i> RSVP (Decline)</a>
                    }
                    else
                    {
                        <a href="@Url.Action("Confirm", "Events", new {id = Model.Id, attend = true})" class="btn btn-sm btn-outline-primary"> <i class="far fa-thumbs-up"></i> RSVP (Accept)</a>
                    }

                }
            }


        </div>
        <div>
            <hr />
            <dl class="row">

                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Event.EventName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Event.EventName)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Event.EventStartDate)
                </dt>
                <dd class="col-sm-10">
                    @Model.Event.EventStartDate.ToString("f")
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Event.EventEndDate)
                </dt>
                <dd class="col-sm-10">
                    @Model.Event.EventEndDate.ToString("f")
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Event.EventVenue)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Event.EventVenue)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Event.EventPoints)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Event.EventPoints)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Event.EventDescription)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Event.EventDescription)
                </dd>
                <dt class="col-sm-4">
                    Status
                </dt>
                <dd class="col-sm-10">
                    @(Model.Event.EventComplete?"Complete" :"Scheduled")
                </dd>
            </dl>
            <hr />
        </div>
    </div>
    <div class="card-footer">
        <a asp-action="Index" class="btn btn-sm btn-outline-success">  <i class="fas fa-long-arrow-alt-left"></i> Back to List</a>
        @*@if (Model.tblEventsHistory.Count() > 0)
        {*@



            @if (Model.Attending)
            {
                <a href="@Url.Action("Confirm", "Events", new { id = Model.Id, attend = false })" class="btn btn-sm btn-outline-danger">  <i class="far fa-thumbs-down"></i> RSVP (Decline)</a>
            }
            else
            {
                <a href="@Url.Action("Confirm", "Events", new { id = Model.Id, attend = true })" class="btn btn-sm btn-outline-primary">  <i class="far fa-thumbs-up"></i>  RSVP (Accept)</a>
            }

        @*}
        else
        {
            <a href="@Url.Action("Confirm", "Events", new { id = Model.Id, attend = true })" class="btn btn-sm btn-outline-primary">  <i class="far fa-thumbs-up"></i>  RSVP (Accept)</a>
        }*@
    </div>
</div>

RpaUi/Areas/Client/Views/Events/Edit.cshtml
@model RpaData.Models.tblEvents

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}
<section class="content">
    <div class="container-fluid">
        <h1>Edit</h1>

        <h4>tblEvents</h4>
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="EventName" class="control-label"></label>
                        <input asp-for="EventName" class="form-control" />
                        <span asp-validation-for="EventName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EventStartDate" class="control-label"></label>
                        <input asp-for="EventStartDate" class="form-control" />
                        <span asp-validation-for="EventStartDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EventEndDate" class="control-label"></label>
                        <input asp-for="EventEndDate" class="form-control" />
                        <span asp-validation-for="EventEndDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EventVenue" class="control-label"></label>
                        <input asp-for="EventVenue" class="form-control" />
                        <span asp-validation-for="EventVenue" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EventPoints" class="control-label"></label>
                        <input asp-for="EventPoints" class="form-control" />
                        <span asp-validation-for="EventPoints" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EventDescription" class="control-label"></label>
                        <input asp-for="EventDescription" class="form-control" />
                        <span asp-validation-for="EventDescription" class="text-danger"></span>
                    </div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Created" class="control-label"></label>
                        <input asp-for="Created" class="form-control" />
                        <span asp-validation-for="Created" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>

    </div>
</section>

RpaUi/Areas/Client/Views/Events/Index.cshtml
@model IEnumerable<RpaData.Models.tblEventsHistory>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}


<div class="content-header">
    <div class="container">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2>Meetings</h2>
            </div><!-- /.col -->
            <div class="col-sm-6">
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead class="thead-light">
                        <tr>
                            <th>
                                Id
                            </th>
                            <th>
                                Meetings List
                            </th>
                        </tr>
                    </thead>
                    <tbody class="table-sm">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    <b>Meeting Name : </b> @Html.DisplayFor(modelItem => item.Event.EventName) <br />

                                    <b>Date : </b>  @item.Event.EventStartDate.ToString("dd-MMM-yyyy HH:mm") to

                                    @item.Event.EventEndDate.ToString("dd-MMM-yyyy HH:mm") <br />

                                    <b>Venue : </b> @Html.DisplayFor(modelItem => item.Event.EventVenue) <br />

                                    <b>Points : </b>@Html.DisplayFor(modelItem => item.Event.EventPoints) <br />
                                    <b>Status : </b>@(item.Event.EventComplete?"Complete" :"Scheduled") <br/>
                                    <hr />
                                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-outline-success"><i class="fas fa-folder-open"></i> View Details</a>
                                    @if (item.Event.tblEventsHistory.Count() > 0)
                                    {
                                        bool? attending = item.Event.tblEventsHistory.FirstOrDefault()?.Attending;
                                        bool? attendend = item.Event.tblEventsHistory.FirstOrDefault()?.AttendedEvent;

                                        @if (!item.Event.EventComplete)
                                        {

                                            @if (attending.Value)
                                            {
                                                <a href="@Url.Action("Confirm", "Events", new {id = item.Event.Id, attend = false})" class="btn btn-sm btn-outline-danger"> <i class="far fa-thumbs-down"></i> RSVP (Decline)</a>
                                            }
                                            else
                                            {
                                                <a href="@Url.Action("Confirm", "Events", new {id = item.Event.Id, attend = true})" class="btn btn-sm btn-outline-primary"> <i class="far fa-thumbs-up"></i> RSVP (Accept)</a>
                                            }
                                        }
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("Confirm", "Events", new { id = item.Event.Id, attend = true })" class="btn btn-sm btn-outline-primary">  <i class="far fa-thumbs-up"></i>  RSVP (Accept)</a>
                                    }



                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="card-footer">

    </div>
        </div>

    </div>
</section>