RpaUi/Controllers/CodesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RpaData.DataContext;
using RpaData.Models;

namespace RpaUi.Controllers
{
    [Authorize]
    public class CodesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CodesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Codes
        public async Task<IActionResult> Index()
        {
            return View(await _context.tblCodes.ToListAsync());
        }

        // GET: Codes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblCodes = await _context.tblCodes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblCodes == null)
            {
                return NotFound();
            }

            return View(tblCodes);
        }

        // GET: Codes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Codes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodeName,CodeEntity,Id")] tblCodes tblCodes)
        {
            var local_time = TimeZoneInfo.ConvertTime(DateTime.Now, TimeZoneInfo.FindSystemTimeZoneById("South Africa Standard Time"));
            tblCodes.Created = local_time;

            if (ModelState.IsValid)
            {
                _context.Add(tblCodes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblCodes);
        }

        // GET: Codes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblCodes = await _context.tblCodes.FindAsync(id);
            if (tblCodes == null)
            {
                return NotFound();
            }
            return View(tblCodes);
        }

        // POST: Codes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CodeName,CodeEntity,Id,Created")] tblCodes tblCodes)
        {
            if (id != tblCodes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblCodes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tblCodesExists(tblCodes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblCodes);
        }

        // GET: Codes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblCodes = await _context.tblCodes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblCodes == null)
            {
                return NotFound();
            }

            return View(tblCodes);
        }

        // POST: Codes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblCodes = await _context.tblCodes.FindAsync(id);
            _context.tblCodes.Remove(tblCodes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool tblCodesExists(int id)
        {
            return _context.tblCodes.Any(e => e.Id == id);
        }
    }
}

RpaUi/Controllers/EmailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RpaData.DataContext;
using RpaData.Models;

namespace RpaUi.Controllers
{
    [Authorize]
    public class EmailsController : Controller
    {
        private readonly ApplicationDbContext db;

        public EmailsController( ApplicationDbContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            tblEmail tblEmail = db.tblEmails.FirstOrDefault();
            if (tblEmail == null)
            {
                tblEmail = new tblEmail();
                return View(tblEmail);
            }
            return View(tblEmail);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("Id,email_smtp,email_address,email_port,email_username,email_password,email_ssl")] tblEmail tblEmails)
        {
            //if (ModelState.IsValid)
            //{
            //    int? id = tblEmails.Id;
            //    if (id == null)
            //    {
            //        return NotFound();
            //    }
            //    tblEmail tblemail = db.tblEmails.FirstOrDefault();
            //    if (tblemail == null)
            //    {
            //        db.tblEmails.Add(tblEmails);
            //        db.SaveChanges();
            //    }
            //    else
            //    {
            //        tblemail.email_address = tblEmails.email_address;
            //        tblemail.email_password = tblEmails.email_password;
            //        tblemail.email_port = tblEmails.email_port;
            //        tblemail.email_smtp = tblEmails.email_smtp;
            //        tblemail.email_ssl = tblEmails.email_ssl;
            //        tblemail.email_username = tblEmails.email_username;
            //        db.SaveChanges();
            //    }
 
            //    return View(tblEmails);
            //}

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(tblEmails);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tblEmailsExists(tblEmails.Id))
                    {
                        db.Add(tblEmails);
                        await db.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblEmails);
        }

        private bool tblEmailsExists(int id)
        {
            return db.tblEmails.Any(e => e.Id == id);
        }
    }
}

RpaUi/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hangfire;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RpaData.DataContext;
using RpaData.Models;
using RpaUi.Interfaces;
using RpaUi.Services;

namespace RpaUi.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMyEmailSender _emailSender;

        public JobsController(ApplicationDbContext context, IMyEmailSender emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }

        // GET: Jobs
        public async Task<IActionResult> Index()
        {
            return View(await _context.tblJobs.ToListAsync());
        }

        // GET: Jobs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblJobs = await _context.tblJobs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblJobs == null)
            {
                return NotFound();
            }

            return View(tblJobs);
        }

        // GET: Jobs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("JobName,JobStatus,JobFrequency,Id,Created")] tblJobs tblJobs)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblJobs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblJobs);
        }

        // GET: Jobs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblJobs = await _context.tblJobs.FindAsync(id);
            if (tblJobs == null)
            {
                return NotFound();
            }
            return View(tblJobs);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("JobName,JobStatus,JobFrequency,Id,Created")] tblJobs tblJobs)
        {
            if (id != tblJobs.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblJobs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tblJobsExists(tblJobs.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblJobs);
        }

        // GET: Jobs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblJobs = await _context.tblJobs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblJobs == null)
            {
                return NotFound();
            }

            return View(tblJobs);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblJobs = await _context.tblJobs.FindAsync(id);
            _context.tblJobs.Remove(tblJobs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ActivateJob()
        {
            RecurringJob.AddOrUpdate(() => BirthdayMessageJobAsync(), "0 2 * * *");
            RecurringJob.AddOrUpdate(() => MeetingReminderJobAsync(), "0 2 * * *");
            RecurringJob.AddOrUpdate(() => MembershipRenewalOneDayJobAsync(), "0 2 * * *");
            RecurringJob.AddOrUpdate(() => MembershipRenewalSevenDaysJobAsync(), "0 2 * * *");

            return RedirectToAction(nameof(Index));
        }

        public async Task BirthdayMessageJobAsync()
        {
            var clients = _context.tblPharmacists.Include(t => t.ApplicationUser).Where(c=>c.ApplicationUser.DateOfBirth.Date == DateTime.Now.Date);

            foreach(var client in clients)
            {
                await _emailSender.SendEmailAsync(client.ApplicationUser.Email, "Birthday Message", "Dear "+ client.ApplicationUser.FullName + "<p>We would like to wish you a Happy Birthday.</p> Regards <p>Retail Pharmacists Asscociation</p>");
            }
        }

        public async Task MembershipRenewalSevenDaysJobAsync()
        {
            var dateSevenDays = DateTime.Now.AddDays(7);
            var clients = _context.tblPharmacists.Include(t => t.ApplicationUser).Where(c => c.dateOfRenewal.Date == dateSevenDays);

            foreach (var client in clients)
            {
                await _emailSender.SendEmailAsync(client.ApplicationUser.Email, "Membership Renewal", "Dear " + client.ApplicationUser.FullName + "<p>We would like to remind you that your membership payment will be due in the next 7 days.</p> Regards <p>Retail Pharmacists Asscociation</p>");
            }
        }

        public async Task MembershipRenewalOneDayJobAsync()
        {
            var dateOneDay = DateTime.Now.AddDays(1);
            var clients = _context.tblPharmacists.Include(t => t.ApplicationUser).Where(c => c.dateOfRenewal.Date == dateOneDay);

            foreach (var client in clients)
            {
                await _emailSender.SendEmailAsync(client.ApplicationUser.Email, "Membership Renewal", "Dear " + client.ApplicationUser.FullName + "<p>We would like to remind you that your membership payment is now due.</p> Regards <p>Retail Pharmacists Asscociation</p>");
            }
        }

        public async Task MeetingReminderJobAsync()
        {
            var dateOneDay = DateTime.Now.AddDays(1);
            var clients = _context.tblEventsHistory.Include(c=>c.tblPharmacists).Include(c=>c.Event).Where(c => c.Event.EventStartDate.Date == dateOneDay);

            foreach (var client in clients)
            {
                await _emailSender.SendEmailAsync(client.tblPharmacists.ApplicationUser.Email, "Meeting Reminder", "Dear " + client.tblPharmacists.ApplicationUser.FullName + "<p>We would like to remind you of the "+ client.Event.EventName+" meeting.</p> Regards <p>Retail Pharmacists Asscociation</p>");
            }
        }

        private bool tblJobsExists(int id)
        {
            return _context.tblJobs.Any(e => e.Id == id);
        }
    }
}

RpaUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RPA - @ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/adminlte.min.css" rel="stylesheet">
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/img/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/jquery-ui-1.10.2.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script src="~/js/site.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>
    <script src='https://js.sentry-cdn.com/e2eafb86dd27e21c499c319f5b8ca227.min.js' crossorigin="anonymous"></script>


    <!-- page script -->
    <script>
        $(function () {
            var selected = [];
            $('#example1').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
                "order": [[0, "desc"]]
            })
            $('#example2').DataTable({
                "order": [[0, "desc"]]
            })
            $('#example3').DataTable()
            $('#example4').DataTable()
            $('#example5').DataTable()
            $('#example6').DataTable()
            $('#example7').DataTable()
            $('#example8').DataTable()
            $('#example9').DataTable()
            $('#example10').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })

            var table = $("#example11").DataTable({
                "ajax": {
                    "url": "/Logs/GetList",
                    "type": "POST",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "Id", "name": "Id" },
                    { "data": "Date", "name": "Date" },
                    { "data": "User", "name": "User" },
                    { "data": "Type", "name": "Type" },
                    { "data": "Status", "name": "Status" },
                    { "data": "Text", "name": "Text" },
                ],
                "processing": "true",
                "serverSide": "true",
                "language": {
                    "processing": "processing... please wait"
                },
                "rowCallback": function (row, data) {
                    if ($.inArray(data.DT_RowData, selected) !== -1) {
                        $(row).addClass('selected');
                    }
                }
            })

            $('table.display').DataTable({
                "order": [[0, "desc"]],
                "columnDefs": [
                    {
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    }]
            });
        })


    </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body class="hold-transition skin-green layout-top-nav">
    <div class="wrapper">

        <nav class="main-header navbar navbar-expand navbar-success navbar-dark">
            <div class="container-fluid">
                @Html.ActionLink("RPA", "Home", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />

                    <ul class="nav navbar-nav  flex-grow-1">
                        <li class="nav-item d-none d-sm-inline-block">@Html.ActionLink("Home", "Home", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                        <li class="nav-item dropdown d-none d-sm-inline-block">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Members
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Pharmacy" asp-action="Index">Pharmacies</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Membership" asp-action="Index">Membership Types</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Meetings
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Meetings" asp-action="Index">Meetings</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Certificates" asp-action="Index">Certificates</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Payments
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Payments" asp-action="Index">Payments</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Invoices" asp-action="Index">Invoices</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                                Communication
                                <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="Communications" asp-action="Index">Emails</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Resources" asp-action="Index">Resources</a>
                                <a class="dropdown-item" asp-area="" asp-controller="ResourceCategories" asp-action="Index">Resource Categories</a>
                                <a class="dropdown-item" asp-area="" asp-controller="MailingLists" asp-action="Index">Mailing List</a>

                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                                Configurations
                                <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="Qualifications" asp-action="Index">Qualifications</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Jobs" asp-action="Index">Jobs</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Codes" asp-action="Index">Codes</a>
                            </div>
                        </li>

                        @{

                            if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                                        Administration
                                        <span class="caret"></span>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-area="" asp-controller="Emails" asp-action="Index">Emails</a>
                                        @Html.ActionLink("Users", "Index", "Users", new { area = "" }, new { @class = "dropdown-item" })
                                        @Html.ActionLink("Roles", "Index", "Roles", new { area = "" }, new { @class = "dropdown-item" })
                                    </div>
                                </li>


                            }

                        }
                    </ul>

                </div>
            </div>

        </nav>

        <div class="content-wrapper">
            <div class="container-fluid">
                <section class="content">
                    @RenderBody()
                </section>
            </div>
        </div>

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.0.5
            </div>
            <strong>Copyright &copy;  <a href="http://mopane.co.zw">Mopane Systems</a>.</strong> All rights
            reserved.
        </footer>

    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

RpaUi/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mopane Systems</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/AdminLTE.css" rel="stylesheet">
    <link href="~/css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="~/css/_all-skins.css" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <!-- jQuery -->
    <script src="~/js/jquery.js"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src='https://js.sentry-cdn.com/e2eafb86dd27e21c499c319f5b8ca227.min.js' crossorigin="anonymous"></script>

</head>
<body class="hold-transition skin-blue layout-top-nav">
    <div class="wrapper">
        <header class="main-header">
        </header>
        <div class="content-wrapper">
            <div class="container">
                <section class="content">
                    @RenderBody()
                </section>
            </div>
        </div>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

RpaUi/Views/Shared/_PublicLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Retail Pharmacists Asscociation</title>
    <meta content="" name="descriptison">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/assets/vendor/cardicons/css/cardicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/venocard/venocard.css" rel="stylesheet">
    <link href="~/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/publicstyle.css" rel="stylesheet">
    <script src='https://js.sentry-cdn.com/e2eafb86dd27e21c499c319f5b8ca227.min.js' crossorigin="anonymous"></script>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
    <script src="~/assets/vendor/counterup/counterup.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/venocard/venocard.min.js"></script>
    <script src="~/assets/vendor/owl.carousel/owl.carousel.min.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>